### ISSUE TITLE
20. Valid Parentheses

### ISSUE THREAD

**Issue by shiqizheng** [shiqizheng/leetcode#2]
https://leetcode.com/problems/valid-parentheses/#/description

Given a string containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.

The brackets must close in the correct order, "()" and "()[]{}" are all valid but "(]" and "([)]" are not.

**Comment by shiqizheng** [comment]
I came up with a naive solution that beats just 9% of all submitted solutions.

**Comment by chakpongchung** [comment]
post the best one you found and move on to next one.

This one we needs only pushing the left paren into the stack
